sudo: required
services:
  - docker

before_install:
  - docker build -t s4bb4n/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true s4bb4n/react-test npm test


after_success:
  - docker build -t s4bb4n/multi-client ./client
  - docker build -t s4bb4n/multi-nginx ./nginx
  - docker build -t s4bb4n/multi-server ./server  
  - docker build -t s4bb4n/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images docker hub
  - docker push s4bb4n/multi-client
  - docker push s4bb4n/multi-nginx
  - docker push s4bb4n/multi-server  
  - docker push s4bb4n/multi-worker 
